[package]

name = "pockystation"

# Should match the latest git tag! This version info is used to set
# the internal `VERSION` string if "git describe" is unavailable.
version = "0.1.0"

authors = ["Lionel Flandrin <lionel@svkt.org>"]
homepage = "https://github.com/simias/pockystation"
repository = "https://github.com/simias/pockystation"
license = "MIT"
keywords = ["emulator", "pockystation"]
edition = "2015"

build = "build.rs"

[dependencies]
log = "0.4"
rustc-serialize = "0.3.19"
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.4"
shaman = "0.1.0"

[dev-dependencies]
flexbuffers = "2.0"
