#[macro_use]
mod box_array;

pub mod bios;
pub mod cpu;
pub mod dac;
pub mod debugger;
pub mod flash;
pub mod interrupt;
mod irda;
pub mod lcd;
mod ram;
pub mod rtc;
mod timer;

#[macro_use]
extern crate log;
extern crate rustc_serialize;
extern crate serde;
extern crate serde_big_array;
extern crate shaman;

/// Maximal frequency of the CPU, this clock can be shifted left by a
/// factor 0...7 to give the effective CPU frequency.
pub const MASTER_CLOCK_HZ: u32 = 31232 << 7;

mod version {
    // VERSION and VERSION_CSTR are generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/version.rs"));
}

use crate::debugger::Debugger;
pub use crate::version::VERSION;
pub use crate::version::VERSION_CSTR;
use bios::Bios;
use cpu::Cpu;
use dac::Dac;
use flash::Flash;
use interrupt::{Interrupt, IrqController};
use irda::Irda;
use lcd::Lcd;
use ram::Ram;
use rtc::Rtc;
use std::panic;
use timer::Timer;

#[derive(serde::Serialize, serde::Deserialize)]
pub struct PocketStation {
    pub cpu: Cpu,
    pub bios: Bios,
    pub flash: Flash,
    ram: Ram,
    pub irq_controller: IrqController,
    timers: [Timer; 3],
    pub rtc: Rtc,
    pub lcd: Lcd,
    dac: Dac,
    irda: Irda,
    cpu_clk_div: u8,
    frame_ticks: u32,
    gpio_out: u8,
    gpo_val: u8,
    batt_ctrl: u8,
    #[serde(skip, default)]
    debugger: Option<Box<dyn Debugger>>,
}

impl PocketStation {
    pub fn new(bios: Bios, flash: Flash, dac: Dac) -> PocketStation
    {
        PocketStation {
            cpu: Cpu::new(),
            bios,
            flash,
            ram: Ram::new(),
            irq_controller: IrqController::new(),
            timers: [
                Timer::new(Interrupt::Timer0),
                Timer::new(Interrupt::Timer1),
                Timer::new(Interrupt::Timer2),
            ],
            rtc: Rtc::new(),
            lcd: Lcd::new(),
            dac,
            irda: Irda::new(),
            cpu_clk_div: 7,
            frame_ticks: 0,
            gpio_out: 0,
            gpo_val: 0,
            batt_ctrl: 0,
            debugger: None,
        }
    }

    pub fn set_debugger(&mut self, d: Box<dyn Debugger>) {
        self.debugger = Some(d);
    }

    pub fn reset(&mut self) {
        self.cpu.reset();
        self.flash.reset();
    }

    pub fn set_frame_ticks(&mut self, ticks: u32) {
        self.frame_ticks = ticks
    }

    pub fn tick(&mut self, cpu_ticks: u32) {
        let master_ticks = cpu_ticks << self.cpu_clk_div;

        self.rtc.tick(&mut self.irq_controller, master_ticks);
        self.dac.tick(master_ticks);

        self.timers[0].tick(&mut self.irq_controller, cpu_ticks);
        self.timers[1].tick(&mut self.irq_controller, cpu_ticks);
        self.timers[2].tick(&mut self.irq_controller, cpu_ticks);

        self.frame_ticks += master_ticks;
    }

    fn with_debugger<F>(&mut self, mut f: F)
        where F: FnMut(&mut PocketStation, &mut dyn Debugger)
    {
        // A little switcharoo to allow a mutable reference to the debugger *and* to the
        // PocketStation object to coexist.
        if let Some(mut d) = self.debugger.take() {
            f(self, &mut *d);

            self.debugger = Some(d);
        }
    }

    pub fn load<A>(&mut self, addr: u32) -> u32
    where
        A: Addressable,
    {
        self.with_debugger(|pks, d| d.memory_read(pks, addr));

        let region = addr >> 24;
        let offset = addr & 0xffffff;

        if (addr & (A::size() as u32 - 1)) != 0 {
            panic!("Misaligned {}bit load at 0x{:08x}", A::size() * 8, addr);
        }

        let unimplemented = || panic!("unhandled load address 0x{:08x}", addr);

        match region {
            0x00 => {
                if self.flash.bios_at_0() {
                    self.bios.load::<A>(offset)
                } else {
                    self.ram.load::<A>(offset)
                }
            }
            0x02 => self.flash.load_virtual::<A>(offset),
            0x04 => self.bios.load::<A>(offset),
            0x06 => self.flash.load_config::<A>(offset),
            0x08 => self.flash.load_raw::<A>(offset),
            0x0a => match offset {
                0x00..=0x10 => self.irq_controller.load::<A>(offset),
                0x800000..=0x800028 => {
                    let timer = (offset >> 8) & 3;

                    self.timers[timer as usize].load::<A>(offset & 0xf)
                }
                _ => unimplemented(),
            },
            0x0b => match offset {
                // CLK MODE
                0 => {
                    let div = 8 - (self.cpu_clk_div + 1);

                    // Reply that the clock is ready (locked?)
                    //
                    // XXX how long does it take for this bit to go up on the real hardware?
                    0x10 | div as u32
                }
                0x800000..=0x80000c => self.rtc.load::<A>(offset & 0xf),
                _ => unimplemented(),
            },
            0x0c => match offset {
                0x800000 => self.irda.load::<A>(0),
                0x800004 => self.irda.load::<A>(4),
                _ => unimplemented(),
            },
            0x0d => match offset {
                0..=0x1ff => self.lcd.load::<A>(offset),
                0x800000 => u32::from(self.gpio_out),
                0x800004 => 0,
                0x800008 => 0,
                // XXX Figure out what this register is exactly
                //
                // This might be the input value for the GPO. If I set the direction of the LED to 0
                // in 0x0D800000 then read this I get 0x12 in this register.
                0x80000c => u32::from(0x10 | ((!self.gpio_out) & 2)),
                0x800010 => self.dac.load::<A>(0),
                0x800014 => self.dac.load::<A>(4),
                0x800020 => u32::from(self.batt_ctrl),
                _ => unimplemented(),
            },
            _ => unimplemented(),
        }
    }

    pub fn store<A>(&mut self, addr: u32, val: u32)
    where
        A: Addressable,
    {
        self.with_debugger(|pks, d| d.memory_write(pks, addr));

        let region = addr >> 24;
        let offset = addr & 0xffffff;

        if (addr & (A::size() as u32 - 1)) != 0 {
            panic!("Misaligned {}bit store at 0x{:08x}", A::size() * 8, addr);
        }

        let unimplemented = || panic!("unhandled store address 0x{:08x}", addr);

        match region {
            0x00 => {
                if !self.flash.bios_at_0() {
                    self.ram.store::<A>(offset, val);
                }
            }
            0x06 => self.flash.store_config::<A>(offset, val),
            0x08 => {
                match offset {
                    // F_KEY1
                    0x2a54 => (),
                    // F_KEY2
                    0x55aa => (),
                    _ => self.flash.store_raw::<A>(offset, val),
                }
            }
            0x0a => match offset {
                0x00..=0x10 => self.irq_controller.store::<A>(offset, val),
                0x800000..=0x800028 => {
                    let timer = (offset >> 4) & 3;

                    self.timers[timer as usize].store::<A>(offset & 0xf, val);
                }
                _ => unimplemented(),
            },
            0x0b => match offset {
                // XXX by looking at the kernel code it seems that
                // values greater than 8 are possible but treated
                // like 8. I need to run some tests on the real
                // hardware to make sure.
                0 => {
                    let v = val.min(8);
                    if v == 0 {
                        // Freezes hardware
                        panic!("CLK DIV 0!");
                    }
                    self.cpu_clk_div = (8 - v - 1) as u8;
                }
                0x800000..=0x80000c => self.rtc.store::<A>(offset & 0xf, val),
                _ => unimplemented(),
            },
            0x0c => match offset {
                0x00 => debug!("COM MODE 0x{:08x}", val),
                0x08 => debug!("COM DATA 0x{:08x}", val),
                0x10 => debug!("COM CTRL1 0x{:08x}", val),
                0x18 => debug!("COM CTRL2 0x{:08x}", val),
                0x800000 => self.irda.store::<A>(0, val),
                0x800004 => self.irda.store::<A>(4, val),
                _ => unimplemented(),
            },
            0x0d => match offset {
                0..=0x1ff => self.lcd.store::<A>(offset, val),
                0x800000 => {
                    // No$ says it's a direction, but it's set to 0xf by the bios which would imply
                    // that 0-3 are output and the rest input, but that doesn't appear to be true.
                    //
                    // However clearing bit 1 does turn the LED off (and setting it light it back
                    // up, so the led is set if we have (CTRL & SET & 2)
                    debug!("GPIO DIR 0x{:08x}", val);
                    self.gpio_out = val as u8;
                }
                0x800004 => self.gpo_val &= !(val as u8),
                0x800008 => {
                    if (val & !2) != 0 {
                        debug!("SETTING GPO {val:x}");
                    }
                    self.gpo_val |= val as u8;
                }
                0x800010 => self.dac.store::<A>(0, val),
                0x800014 => self.dac.store::<A>(4, val),
                0x800020 => {
                    if val != 0 {
                        debug!("BATT CTRL 0x{:08x}", val);
                    }

                    // Set to 0 by the BIOS
                    //
                    // Writing 0xff doesn't seem to do anything, reads back 7
                    // writing 0x1 reads back 1
                    // Writing 0x2 displays the "low battery" indicator on the screen, and the
                    //             console won't respond to COM. Buttons remain active.
                    // Writing 0x3 seems to crash/freeze the console (no reset, screen shuts down)
                    // Writing 0x4 reads back 4
                    // Writing 0x5 reads back 5 and the screen blinks, looks dimmed and displays the
                    //             low battery indicator
                    // Writing 0x6 reads back 6
                    //
                    // So apparently setting
                    self.batt_ctrl = (val as u8) & 7
                }
                _ => unimplemented(),
            },
            _ => unimplemented(),
        }
    }

    // Returns true if the red LED above the screen is lit
    pub fn led_state(&self) -> bool {
        self.gpio_out & self.gpo_val & 2 != 0
    }

    /// Load a memory location without side-effect, useful for
    /// debugging.
    pub fn examine<A: Addressable>(&mut self, addr: u32) -> u32 {
        // Catch panics (probably caused by unimplemented memory
        // regions). We don't want to crash the code if the debugger
        // reads from a weird address.
        //
        // XXX Remove that when the entire address space is
        // implemented.
        let r = panic::catch_unwind(panic::AssertUnwindSafe(|| self.load::<A>(addr)));

        r.unwrap_or(0xbadbadbd)
    }

    /// Run CPU for `master_ticks` master clock periods
    pub fn run_ticks(&mut self, master_ticks: u32) {
        while self.frame_ticks < master_ticks {
            cpu::run_next_instruction(self);
        }

        self.set_frame_ticks(0);
    }


    pub fn trigger_break(&mut self) {
        self.with_debugger(|_pks, d| d.trigger_break())
    }
}

/// Trait representing the attributes of a memory access
pub trait Addressable {
    /// Retreive the size of the access in bytes
    fn size() -> u8;
}

/// Marker for Byte (8bit) access
pub struct Byte;

impl Addressable for Byte {
    fn size() -> u8 {
        1
    }
}

/// Marker for HalfWord (16bit) access
pub struct HalfWord;

impl Addressable for HalfWord {
    fn size() -> u8 {
        2
    }
}

/// Marker for Word (32bit) access
pub struct Word;

impl Addressable for Word {
    fn size() -> u8 {
        4
    }
}
