#[macro_use]
mod box_array;

pub mod cpu;
pub mod dac;
pub mod debugger;
pub mod interrupt;
mod irda;
pub mod lcd;
pub mod memory;
pub mod rtc;
mod timer;

#[macro_use]
extern crate log;
extern crate rustc_serialize;
extern crate serde;
extern crate serde_big_array;
extern crate shaman;

/// Maximal frequency of the CPU, this clock can be shifted left by a
/// factor 0...7 to give the effective CPU frequency.
pub const MASTER_CLOCK_HZ: u32 = 31232 << 7;

mod version {
    // VERSION and VERSION_CSTR are generated by build.rs
    include!(concat!(env!("OUT_DIR"), "/version.rs"));
}

pub use version::VERSION;
pub use version::VERSION_CSTR;
